# Generated by Django 4.1.3 on 2022-11-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_layout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author", name="birth_year", field=models.IntegerField(),
        ),
    ]
