# Generated by Django 4.1.3 on 2022-11-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_layout", "0002_alter_author_birth_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ebook", old_name="ebook_cotent", new_name="ebook_content",
        ),
    ]
