# Generated by Django 4.1.3 on 2022-12-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_layout", "0002_alter_ebook_year_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebook", name="year_published", field=models.IntegerField(),
        ),
    ]
