# Generated by Django 4.1.3 on 2022-11-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_layout", "0003_rename_ebook_cotent_ebook_ebook_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofileinfo",
            old_name="city_of_residece",
            new_name="city_of_residence",
        ),
    ]
