# Generated by Django 4.1.3 on 2022-11-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "library_layout",
            "0004_rename_city_of_residece_userprofileinfo_city_of_residence",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofileinfo", name="city_of_residence",),
        migrations.RemoveField(model_name="userprofileinfo", name="date_of_birth",),
    ]
