# Generated by Django 4.1.3 on 2022-11-22 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_layout", "0005_remove_userprofileinfo_city_of_residence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileinfo",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                upload_to="profile_pics",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
