# Generated by Django 4.1.3 on 2022-11-22 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_layout", "0006_alter_userprofileinfo_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofileinfo", name="country_of_residence",
        ),
        migrations.AlterField(
            model_name="userprofileinfo",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                upload_to="profile_pics",
                validators=[django.core.validators.FileExtensionValidator(["png"])],
            ),
        ),
    ]
