# Generated by Django 4.1.3 on 2022-11-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_layout", "0007_remove_userprofileinfo_country_of_residence_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofileinfo", name="profile_pic",),
    ]
