# Generated by Django 4.1.3 on 2022-11-22 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_layout", "0008_remove_userprofileinfo_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
